apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "orchestrator.parodos.dev/v1alpha1",
          "kind": "Orchestrator",
          "metadata": {
            "name": "orchestrator-sample"
          },
          "spec": {
            "orchestrator": {
              "devmode": false,
              "namespace": "sonataflow-infra",
              "sonataPlatform": {
                "dataIndex": {
                  "image": "quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest"
                },
                "jobService": {
                  "image": "quay.io/kiegroup/kogito-jobs-service-postgresql-nightly:latest"
                },
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "1Gi"
                  },
                  "requests": {
                    "cpu": "250m",
                    "memory": "64Mi"
                  }
                }
              },
              "sonataflows": [
                {
                  "image": "quay.io/orchestrator/serverless-workflow-greeting:latest",
                  "name": "greeting"
                }
              ]
            },
            "postgres": {
              "authSecret": {
                "name": "sonataflow-psql-postgresql",
                "passwordKey": "postgres-password",
                "userKey": "postgres-username"
              },
              "database": "sonataflow",
              "serviceName": "sonataflow-psql-postgresql",
              "serviceNamespace": "sonataflow-infra"
            },
            "rhdhOperator": {
              "enabled": true,
              "github": {
                "clientId": "",
                "clientSecret": "",
                "token": ""
              },
              "k8s": {
                "clusterToken": "",
                "clusterUrl": ""
              },
              "subscription": {
                "channel": "alpha",
                "installPlanApproval": "Automatic",
                "namespace": "backstage-system",
                "pkgName": "backstage-operator",
                "source": "rhdh-operator",
                "sourceImage": "quay.io/janus-idp/operator-catalog:0.1.0",
                "sourceNamespace": "openshift-marketplace"
              }
            },
            "serverlessOperator": {
              "enabled": true,
              "subscription": {
                "channel": "stable",
                "installPlanApproval": "Automatic",
                "namespace": "openshift-serverless",
                "pkgName": "serverless-operator",
                "sourceNamespace": "openshift-marketplace"
              }
            },
            "sonataFlowOperator": {
              "enabled": true,
              "subscription": {
                "channel": "alpha",
                "installPlanApproval": "Automatic",
                "namespace": "openshift-operators",
                "pkgName": "sonataflow-operator",
                "source": "sonataflow-operator",
                "sourceImage": "quay.io/masayag/kogito-serverless-operator-catalog:v999.0.0-snapshot",
                "sourceNamespace": "openshift-marketplace"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-03-27T21:42:46Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: operator.v0.0.1
  namespace: placeholder
spec:
  minKubeVersion: 1.27.0
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Orchestrator
      name: orchestrators.orchestrator.parodos.dev
      description: Parodos Orchestrator Operator
      version: v1alpha1
  description: Parodos Orchestrator
  displayName: Parodos Orchestrator
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAJMAAACTCAYAAACK5SsVAAAJ1UlEQVR4nOzde2xW5R0H8O9zbu/70kIptIWquAKisA5QEebKZdNsLjqy6G5x2SAmcyGbDMwuLjgyp3H7S7eIy9yYk+HGDGa6zTET3Fy80nFTGXihlAIqRSj0RqXv5ZzzLH07u1J6zvuWPn0u3e+TkKDPad9vzNdze895HgcF8HVIYHz5JNhhwW3J/4HA8tHedpytQmbgEBtse76hJhk6nd8E+HIOzJUSkhiFAXvA2UarvfUXHxTrnDLxTWXT/ND6KwM+rCQlMQoD9lk8/Cxb3nHorDLxjWMnBpazA8A0dfGIgRptK1xg9f83ge3cS0Ui5+GSILTu6dsz8ccrS4OM3wIgqTYXMVSmb8/kZ4M6KhIZhkRfmRgPL1SbhZjuf2UC89RGIaazVAcgoweViQhDZSLCUJmIMFQmIgyViQhDZSLCUJmIMFQmIgyViQhDZSLCUJmIMNq8JJCbcweC8tmqYxTH7wTzu3v/5E4DmRZYnU1gpw/Dev9dgAeqEyqhTZmC8loEk+tUxxi+IAOrbR+c4/WwWrbDPrkLCLKqU0mhTZlGDTuBsGIeshXzAKzMF8lpfhbO4T/BPvY8wH3VCUcMlWmk2R78Kdfn/7DuFrhNj8E58ChYpk11MuHoBFwinqpEtnYVupe+gOzcNeCpCtWRhKIyKcCdMcjNvBXdNzyPXO2q/KFxNKAyKcSdJLIfWY3u655CUHW16jjD1veqU/C78hUc+KWqID3/t8JyVX380DAb3CkF3FLAG4ugtAZ87DSE46bnT765N+48fimH9+Z6uHt/auxJujYn4Mw/ozrCkLBMa9/frRPb+w3YCMtr4U/6GIKLlyIcX+xb9gzZWSvgV85Hon41rDPN4kOPMG32TKMVL7sMualfhD/tS+BuSVE/w9KnkHzxVlit/x7xfCLROdMIYx374b12L1JbFsPd9wBYtr3gz/DkRKSv2YSgerGUjKJQmSRh2Q54r69D6ulPwm3aDPAwdvuec8j0ol/Dn/IZaRmHi8okGcu0wdt5J1LPfgHW6ab4jS0XmavvR1C9RFa8YaEyKWKd2oPU1qW9e6nYDV1k6h7KXyXqjsqkUpDJ76W83T+MfdKAO0mkF/0K4Ri9p4OgMmnAbdyE5Eu35csVhSfKkVn4c8DSd0oIKpMm7Oa/I/nC12IfVwknzEF2zh1Scw0FlUkj9ol6JOtXxx7ycpfdgmDyQqm5ikVl0ox99Bl4u++K2YIhO+9uLb8cpjJpyD34GJzDT0SOh6VTkZ25QmqmYlCZNNWzd7I6GyPHc7O+gXDMBVIzFUJl0hTzu5H413ejz59sD/7Mr8uOFYvKpDGrbS/cg9E3NXPTbgZPVknNFIfKpDl3733Rz4vbXv6JTV1QmTTHsh1wDvw2ctyf+nltruyoTAZwGzaCZTsHHePeePjV10jPNBgqkwFY7jScmC+E/ZobpeaJQmUyhHPoj5FjQfXHi36KcyRRmQxhdTbmXzsffNBDWLlAdqRzY6gOQIrnvPO3yLGgSv33dVQmg9jv1UeOBZPUv3enzatOJrw313OZrpLV/nr+hYSeK7iBwrJL8/edVM64ok2ZMgsfQjB5keoYMThKNl+iOEII6+SrCC4Y5FYAs8FLa8A6GlQky6PDnGHiXkIIxk6VmmUgKpNhWOfByLFw3HSpWQaiMhnG6no7ejAxQWaUc1CZDJOfQzNCfjINhahMpsl1RY+5asukzdVcHLv5H2BBTspnBZPqwL0yKZ91PlgQXab87RWFjChTYseas6awGUnd1/1F6zLxuKWUQ7Wz+tJhzjAs5lDG4g6BElCZDBP3dIDqCdOoTIYJk5Mix+Ku9GSgMhkm7sYk6zoiNctAVCbD8JivTKzTh6RmOefzlX46GbKgvDZyjFGZSLF4ciJ42YxBx1j6FFj6pPRM/VGZDBJU1fWfIPksdssO6XkGojIZZNDnmP7LOrFNapZBM6gOQIrDnRSCCz8VOR73SK8sVCZDBBfdEPndW89VnNWl9uQbVCZz5GYsixyzDz8pNUsUKpMBgurFCCdErV/M4Rx5SnKiwVGZDJCdtTJyzD6+rXeRaQ1QmTTnT7keYeVVkePuW+ul5olDZdIYd0uQu2Jt5LjVthf2ey9LzRSHyqSx3OzvIExNjhz39j2YP2fSBZVJU8EF1yI3Y3nkuNWyE3bzP6VmKoTKpKGwZAoyH70v8qsThDkkdq3Vaq8EKpN+8mukLPlN7HPo3v5HYqd1VoXKpBHupJBe/HDsA3A9JXLeeFBqrmJRmTTB3bHI9BRp4uWR2zA/jeS2lfk5wnVkxKtOox1PVSC9ZEPBlca9V+4C6zggLddQUZkUCyuuRKZuHcJUdex2bsOG2HktdUBlUoYhd+ktyM79fsFJzpy3t8B77SfSkp0vKpMCYXktMlfejbDiioLb2sdeRGL79wquNq4DKpNEPFmFXO1tyE3/cn6mt0Lso1uRrL9d+WvfxaIySRCWXJxfgSk3hKUp3MY/wHvlR7GrYuqGyjRCei71g4s+Db/mJgSVCwBW5F0Y7sPbez/cN/V5GqBYVCYhGMIx1eBl0xFWzIdfVYdw4myADe0/r9V9DIltq2Gd3D1iSUeSEWXKXr4GTNKUxDxydUmG7FU/7t3GLel9HtspQZgoB0o+BO4kh/W5zrtb4e36QfRyYAYwokx+zedUR8jLTb9Z+O+0uo7Ae/Ue2M3PCf/dshlRptGoZw/kNDwCb//DSieCF4nKJBlLn4TbuAlOwwblU+CIRmWSgfuwj70E58if4RzdOmr2RANRmUYIy3bAatkB+/jLcN55Oj+xxGhHZRquIAMr3QLWeQhWVxNYZxPsU3tgtb9h1A1HEYwoU+qZGwFJKyqlF6+PmLaGI7Xl2r5/YrmO3jkkQzlTSpvAiDKxM0elTd3Mwkzkk9XW+zFLTRB60pKIQ2UiwlCZiDBUJiIMlYkIQ2UiwlCZiDBUJiIMlYkIQ2UiwlCZiDBUJiIMlYkIQ2UiwlCZiDBUJiIMlYkIQ2UiwlCZiDBUJiKMES8UhONngWU75XxYxAKBpDAjypT+xKOqI5Ai0GGOCENlIsJQmYgwVCYiDJWJCKPN1Zx97DltFi4enF5ru+lImzK5DRtURyDDRIc5IgyViQhDZSLCUJmIMFQmIgyViQhDZSLCUJmIMFQmIky/MjH6voAMS1+ZOOeSnoslo1VfmUKbv6U2CjEd++AvnIMFvy9vAHCJ2kjERBy8oW/PxBg4GFurNhIxFYN151lXc85XWzdzsAfURSIm4uA/c5a1PnHOrQF3WevtjPPVAOiEnBTSwYBvucvav43+50wD8cfHTQjSzk1gfD4YJkiNSPTG0QrOdtp28CT7Soe5y50Tff0nAAD//7NStz6YKQtyAAAAAElFTkSuQmCC"
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        - apiGroups:
          - operators.coreos.com
          resources:
          - operatorgroups
          - subscriptions
          - catalogsources
          verbs:
          - list
          - get
          - delete
          - update
          - create
          - patch
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - ingresses
          verbs:
          - get
          - list
        - apiGroups:
          - operator.knative.dev
          resources:
          - knativeeventings
          - knativeservings
          verbs:
          - get
          - create
          - delete
          - list
          - watch
          - patch
        - apiGroups:
          - serving.knative.dev
          resources:
          - services
          verbs:
          - list
          - get
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - get
          - list
          - create
          - delete
          - watch
        - apiGroups:
          - rhdh.redhat.com
          resources:
          - backstages
          verbs:
          - get
          - create
          - delete
          - list
          - watch
          - patch
        - apiGroups:
          - sonataflow.org
          resources:
          - sonataflows
          - sonataflowclusterplatforms
          - sonataflowplatforms
          verbs:
          - get
          - list
          - create
          - delete
          - watch
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - get
          - list
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - list
          - get
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - list
          - get
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - delete
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - delete
          - create
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - delete
          - create
          - list
          - watch
        - apiGroups:
          - orchestrator.parodos.dev
          resources:
          - orchestrators
          - orchestrators/status
          - orchestrators/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - argoproj.io
          resources:
          - appprojects
          verbs:
          - get
          - create
          - list
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: orchestrator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: operator
          control-plane: controller-manager
        name: orchestrator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=operator
                image: quay.io/jordigilh/orchestrator-controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: orchestrator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: orchestrator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - parodos
  - orchestrator
  links:
  - name: Operator
    url: https://github.com/parodos-dev/orchestrator-helm-operator
  maturity: alpha
  provider:
    name: Red Hat
    url: https://parodos.dev
  version: 0.0.1
