apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: orchestrator-operator
    app.kubernetes.io/instance: orchestrator-operator-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: orchestrator-operator
    control-plane: orchestrator-operator
  name: orchestrator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: orchestrator-operator
status:
  loadBalancer: {}
