apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - patch
  - update
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - update
  - get
  - list
  - patch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - subscriptions
  - catalogsources
  verbs:
  - list
  - get
  - delete
  - update
  - create
  - patch
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - operator.knative.dev
  resources:
  - knativeeventings
  - knativeservings
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - patch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - list
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - create
  - delete
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - backstages
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - patch
- apiGroups:
  - sonataflow.org
  resources:
  - sonataflows
  - sonataflowclusterplatforms
  - sonataflowplatforms
  verbs:
  - get
  - list
  - create
  - delete
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - get
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - delete
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - delete
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - create
  - list
  - watch
##
## Rules for orchestrator.parodos.dev/v1alpha1, Kind: Orchestrator
##
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators
  - orchestrators/status
  - orchestrators/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - get
  - create
  - list
#+kubebuilder:scaffold:rules
