apiVersion: orchestrator.parodos.dev/v1alpha1
kind: Orchestrator
metadata:
  name: orchestrator-sample
spec:
  # Default values copied from <project_dir>/helm-charts/orchestrator/values.yaml
  orchestrator:
    devmode: false
    namespace: sonataflow-infra
    sonataPlatform:
      dataIndex:
        image: quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest
      jobService:
        image: quay.io/kiegroup/kogito-jobs-service-postgresql-nightly:latest
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 64Mi
    sonataflows:
    - image: quay.io/orchestrator/serverless-workflow-greeting:latest
      name: greeting
  postgres:
    authSecret:
      name: sonataflow-psql-postgresql
      passwordKey: postgres-password
      userKey: postgres-username
    database: sonataflow
    serviceName: sonataflow-psql-postgresql
    serviceNamespace: sonataflow-infra
  rhdhOperator:
    enabled: true
    github:
      clientId: ""
      clientSecret: ""
      token: ""
    k8s:
      clusterToken: ""
      clusterUrl: ""
    subscription:
      channel: alpha
      installPlanApproval: Automatic
      namespace: backstage-system
      pkgName: backstage-operator
      source: rhdh-operator
      sourceImage: quay.io/janus-idp/operator-catalog:0.1.0
      sourceNamespace: openshift-marketplace
  serverlessOperator:
    enabled: true
    subscription:
      channel: stable
      installPlanApproval: Automatic
      namespace: openshift-serverless
      pkgName: serverless-operator
      sourceNamespace: openshift-marketplace
  sonataFlowOperator:
    enabled: true
    subscription:
      channel: alpha
      installPlanApproval: Automatic
      namespace: openshift-operators
      pkgName: sonataflow-operator
      source: sonataflow-operator
      sourceImage: quay.io/masayag/kogito-serverless-operator-catalog:v999.0.0-snapshot
      sourceNamespace: openshift-marketplace
  
  
