{{- $ns := .Values.orchestrator.namespace }}
{{- if .Values.orchestrator.devmode }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd.namespace }}
---
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-fail
    "helm.sh/hook-weight": "2" # Is created after the job to wait for the crd to be available  
spec:
  build:
    template:
      resources:
        requests:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.requests.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.requests.cpu }}
        limits:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.limits.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.limits.cpu }}
  services:
    dataIndex:
      enabled: true
    jobService:
      enabled: true
{{- else }}
---
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-fail
    "helm.sh/hook-weight": "2" # Is created after the job to wait for the crd to be available  
spec:
  build:
    template:
      resources:
        requests:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.requests.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.requests.cpu }}
        limits:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.limits.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.limits.cpu }}
  services:
    dataIndex:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: {{ .Values.postgres.authSecret.name }}
            userKey: {{ .Values.postgres.authSecret.userKey }}
            passwordKey: {{ .Values.postgres.authSecret.passwordKey }}
          serviceRef:
            name: {{ .Values.postgres.serviceName }}
            namespace: {{ .Values.postgres.serviceNamespace }}
    jobService:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: {{ .Values.postgres.authSecret.name }}
            userKey: {{ .Values.postgres.authSecret.userKey }}
            passwordKey: {{ .Values.postgres.authSecret.passwordKey }}
          serviceRef:
            name: {{ .Values.postgres.serviceName }}
            namespace: {{ .Values.postgres.serviceNamespace }}
{{- end }}
{{ include "wait-for-crd-available" (dict "releaseName" .Release.Name "releaseNamespace" .Release.Namespace "apiGroup" "sonataflow.org" "resourceName" "sonataflowplatforms") }}
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-fail
    "helm.sh/hook-weight": "2" # Is created after the job to wait for the crd to be available 
spec:
  platformRef:
    name: sonataflow-platform
    namespace: {{ $ns }}
{{ include "wait-for-crd-available" (dict "releaseName" .Release.Name "releaseNamespace" .Release.Namespace "apiGroup" "sonataflow.org" "resourceName" "sonataflowclusterplatforms") }}
